- name: Update yum cache
  yum:
    update_cache: yes
    state: latest


- name: Add Jenkins repo
  yum_repository:
    name: "Jenkins"
    description: "Jenkins Yum repo"
    baseurl: "{{ jenkins.repo_URL }}"
    state: present

- name: Add Jenkins key
  rpm_key:
    key: "{{ jenkins.key_rpm }}"
    state: present


- name: Install java
  yum:
    name: "{{ java }}"
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present 

- name : Start Jenkins
  service: 
    name: jenkins
    enabled: true
    state: started